/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IDataVerifierAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getOracleAddress"
      | "verifyOwnership"
      | "verifyTransferValidity"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getOracleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyOwnership",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyTransferValidity",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getOracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyTransferValidity",
    data: BytesLike
  ): Result;
}

export interface IDataVerifierAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): IDataVerifierAdapter;
  waitForDeployment(): Promise<this>;

  interface: IDataVerifierAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getOracleAddress: TypedContractMethod<[], [string], "view">;

  verifyOwnership: TypedContractMethod<
    [data: BytesLike],
    [boolean],
    "nonpayable"
  >;

  verifyTransferValidity: TypedContractMethod<
    [data: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getOracleAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyOwnership"
  ): TypedContractMethod<[data: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyTransferValidity"
  ): TypedContractMethod<[data: BytesLike], [boolean], "nonpayable">;

  filters: {};
}
