/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DataVerifierAdapterFixed } from "./DataVerifierAdapterFixed";
export type { IDataVerifierAdapter } from "./IDataVerifierAdapter";
