/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDataVerifierAdapter,
  IDataVerifierAdapterInterface,
} from "../../../../contracts/interfaces/IDataVerifierAdapterFixed.sol/IDataVerifierAdapter";

const _abi = [
  {
    inputs: [],
    name: "getOracleAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "verifyOwnership",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "verifyTransferValidity",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDataVerifierAdapter__factory {
  static readonly abi = _abi;
  static createInterface(): IDataVerifierAdapterInterface {
    return new Interface(_abi) as IDataVerifierAdapterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDataVerifierAdapter {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IDataVerifierAdapter;
  }
}
