/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iDataVerifierAdapterSol from "./IDataVerifierAdapter.sol";
export { IOracle__factory } from "./IOracle__factory";
