/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DataVerifierAdapter } from "./DataVerifierAdapter";
export type { IDataVerifierAdapter } from "./IDataVerifierAdapter";
