/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { OracleStub } from "./OracleStub";
export * as factories from "./factories";
export type { IOracle } from "./interfaces/IOracle";
export { IOracle__factory } from "./factories/interfaces/IOracle__factory";
export { OracleStub__factory } from "./factories/OracleStub__factory";
